config/routes.rb
Geriatrics::Application.routes.draw do
  resources :funeral_arrangements

  resources :military_histories

  resources :legal_documents

  resources :doctors

  devise_for :users

  get "providers/attorney_insurance_providers"

  get "providers/financial_providers"

  get "providers/healthcare_providers"

  get "providers/caregiver_providers"

 get "providers/attorney_Insurance"

  resources :personal_properties

  resources :legal_doucuments

  resources :insurances

  resources :loans_credit_cards

  resources :banking_financials

  resources :medical_histories

  resources :medications

  resources :clients

  get "post/home"

  get "post/Geriatric_Care_Manager"

  get "post/Geriatric_Client"

  get "post/Providers"

  get "post/Medical_History"

  get "post/Banking_And_Financial"

  get "post/Other_Documents"

  

  

 
end

app/models/banking_financial.rb
class BankingFinancial < ActiveRecord::Base
  belongs_to :user
  attr_accessible :account_Holders, :account_No, :account_type, :beneficiary, :date_Of_Birth, :institution_Information, :social_Security
  validates_presence_of :account_Holders, :account_No, :account_type, :beneficiary, :date_Of_Birth,:social_Security 
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user
  attr_accessible :allergies_info, :blood_type, :date_of_birth, :details_DNR, :firstname, :lastname, :name_healthcare_proxy, :organization, :phone_no

  validates_presence_of :allergies_info, :blood_type, :date_of_birth, :details_DNR, :firstname, :lastname, :name_healthcare_proxy, :organization, :phone_no
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  attr_accessible :address, :name
end

app/models/doctors.rb
class Doctors < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
  belongs_to :user
  attr_accessible :account_Holders, :account_No, :account_Type, :beneficiary, :document, :institution_Information, :insurance_Card
 validates_presence_of :account_Holders, :account_No, :account_Type, :beneficiary, :document, :institution_Information, :insurance_Card
end

app/models/legal_document.rb
class LegalDocument < ActiveRecord::Base
  attr_accessible :do_ot_resuscitate, :health_care_directive, :letter_of_authorization, :location_of_original, :pension_papers, :power_of_attorney, :trust, :will, :wishes
end

app/models/legal_doucument.rb
class LegalDoucument < ActiveRecord::Base
  attr_accessible :do_Not_Resuscitate, :healthcare_Directive, :letter_of_Authorization, :location_of_Original, :pension_Papers, :power_of_Attorney, :trust, :will, :wishes
 validates_presence_of :do_Not_Resuscitate, :healthcare_Directive, :letter_of_Authorization, :location_of_Original, :pension_Papers, :power_of_Attorney, :trust, :will, :wishes
end

app/models/loans_credit_card.rb
class LoansCreditCard < ActiveRecord::Base
  belongs_to :user
  attr_accessible :account_Number, :account_Type, :institution_Information
 validates_presence_of :account_Number, :account_Type, :institution_Information
end

app/models/medical_history.rb
class MedicalHistory < ActiveRecord::Base
  belongs_to :user
  attr_accessible :comments, :date, :date_Of_Onset, :diagnosis_procedure, :documents, :physician, :updater
 validates_presence_of :comments, :date, :date_Of_Onset, :diagnosis_procedure, :documents, :physician, :updater
end

app/models/medication.rb
class Medication < ActiveRecord::Base
  belongs_to :user
  attr_accessible :currently_Taking, :dosage, :frequency, :medication_Photo, :name_Of_Medication, :pharmacy, :prescrbing_Physician, :prescription, :special_Instruvtions
 validates_presence_of :currently_Taking, :dosage, :frequency, :medication_Photo, :name_Of_Medication, :pharmacy, :prescrbing_Physician, :prescription, :special_Instruvtions
end

app/models/military_history.rb
class MilitaryHistory < ActiveRecord::Base
  attr_accessible :_number, :active_or_reserve, :branch_of_service, :military_contact_name, :military_contact_phone, :notes, :pension_or_benefits_phone, :pension_qualified?, :years_of_service
end

app/models/personal_property.rb
class PersonalProperty < ActiveRecord::Base
  belongs_to :user
  attr_accessible :address_Line1, :address_Line2, :city, :item_Location, :make, :model, :notes, :notes, :notes_Collectibles_Valuable, :property_Nickname, :state, :stem_Description, :vehicles, :year, :zip
 validates_presence_of :address_Line1, :address_Line2, :city, :item_Location, :make, :model, :notes, :notes, :notes_Collectibles_Valuable, :property_Nickname, :state, :stem_Description, :vehicles, :year, :zip
end

app/models/user.rb
class User < ActiveRecord::Base
has_one :banking_financial
has_one :client
has_one :insurance
has_one :loans_credit_card
has_one :medical_history
has_one :medication
has_one :personal_property

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/banking_financials_controller.rb
class BankingFinancialsController < ApplicationController
  # GET /banking_financials
  # GET /banking_financials.json
  def index
    @banking_financials = BankingFinancial.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @banking_financials }
    end
  end

  # GET /banking_financials/1
  # GET /banking_financials/1.json
  def show
    @banking_financial = BankingFinancial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @banking_financial }
    end
  end

  # GET /banking_financials/new
  # GET /banking_financials/new.json
  def new
    @banking_financial = BankingFinancial.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @banking_financial }
    end
  end

  # GET /banking_financials/1/edit
  def edit
    @banking_financial = BankingFinancial.find(params[:id])
  end

  # POST /banking_financials
  # POST /banking_financials.json
  def create
    @banking_financial = BankingFinancial.new(params[:banking_financial])

    respond_to do |format|
      if @banking_financial.save
        format.html { redirect_to @banking_financial, notice: 'Banking financial was successfully created.' }
        format.json { render json: @banking_financial, status: :created, location: @banking_financial }
      else
        format.html { render action: "new" }
        format.json { render json: @banking_financial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /banking_financials/1
  # PUT /banking_financials/1.json
  def update
    @banking_financial = BankingFinancial.find(params[:id])

    respond_to do |format|
      if @banking_financial.update_attributes(params[:banking_financial])
        format.html { redirect_to @banking_financial, notice: 'Banking financial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @banking_financial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banking_financials/1
  # DELETE /banking_financials/1.json
  def destroy
    @banking_financial = BankingFinancial.find(params[:id])
    @banking_financial.destroy

    respond_to do |format|
      format.html { redirect_to banking_financials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banking_financials_helper.rb
module BankingFinancialsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/banking_financials/_form.html.erb
<%= form_for(@banking_financial) do |f| %>
  <% if @banking_financial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banking_financial.errors.count, "error") %> prohibited this banking_financial from being saved:</h2>

      <ul>
      <% @banking_financial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :social_Security %><br />
    <%= f.number_field :social_Security %>
  </div>
  <div class="field">
    <%= f.label :date_Of_Birth %><br />
    <%= f.datetime_select :date_Of_Birth %>
  </div>
  <div class="field">
    <%= f.label :account_type %><br />
    <%= f.text_field :account_type %>
  </div>
  <div class="field">
    <%= f.label :account_No %><br />
    <%= f.number_field :account_No %>
  </div>
  <div class="field">
    <%= f.label :account_Holders %><br />
    <%= f.text_field :account_Holders %>
  </div>
  <div class="field">
    <%= f.label :beneficiary %><br />
    <%= f.text_field :beneficiary %>
  </div>
  <div class="field">
    <%= f.label :institution_Information %><br />
    <%= f.text_area :institution_Information %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
           

app/views/banking_financials/edit.html.erb
<div id="big_wrapper">
		<header id="top_header1">
		<h1> Banking Financial</h1><%=image_tag "image(3).gif" %>
</header>
  </div>
<nav id="top_menuf">
<%=render :partial=>'shared/navigation'%>
  </nav>
    <h1>Edit Banking Financial</h1>
    <%= render 'form' %>
<%= link_to 'Show', @banking_financial %> |
<%= link_to 'Back', banking_financials_path %>

app/views/banking_financials/index.html.erb
<div id="big_wrapper">
		<header id="top_header1">
		<h1> Banking Financial</h1><%=image_tag "image(3).gif" %>
</header>
  </div>
<nav id="top_menuf">
<%=render :partial=>'shared/navigation'%>
  </nav>
<h1>Index Banking Financial</h1>

<table>
 <!-- <tr>
    <th>Social security</th>
    <th>Date of birth</th>
    <th>Account type</th>
    <th>Account no</th>
    <th>Account holders</th>
    <th>Beneficiary</th>
    <th>Institution information</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>-->

<% @banking_financials.each do |banking_financial| %>
  <tr>
    <td><% banking_financial.social_Security %></td>
    <td><% banking_financial.date_Of_Birth %></td>
    <td><% banking_financial.account_type %></td>
    <td><% banking_financial.account_No %></td>
    <td><% banking_financial.account_Holders %></td>
    <td><% banking_financial.beneficiary %></td>
    <td><% banking_financial.institution_Information %></td>
    <td><% link_to 'Show', banking_financial %></td>
    <td><% link_to 'Edit', edit_banking_financial_path(banking_financial) %></td>
    <td><% link_to 'Destroy', banking_financial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Banking financial', new_banking_financial_path %>

app/views/banking_financials/new.html.erb
<div id="big_wrapper">
		<header id="top_header1">
		<h1>Banking Financial</h1><%=image_tag "image(3).gif" %>
</header>
  </div>
<nav id="top_menuf">
<%=render :partial=>'shared/navigation'%>
  </nav>

<h2> New Banking Financial</h2>

<%= render 'form' %>

<!--<#%= link_to 'Back', banking_financials_path %>-->
<%= link_to 'New Client', clients_path %>

app/views/banking_financials/show.html.erb
<div id="big_wrapper">
		<header id="top_header1">
		<h1> Banking Financial</h1><%=image_tag "image(3).gif" %>
</header>
  </div>
<nav id="top_menuf">
<%=render :partial=>'shared/navigation'%>
  </nav>
    <h1>Show Banking Financial</h1>
<p id="notice"><%= notice %></p>

<p>
  <b>Social security:</b>
  <%= @banking_financial.social_Security %>
</p>

<p>
  <b>Date of birth:</b>
  <%= @banking_financial.date_Of_Birth %>
</p>

<p>
  <b>Account type:</b>
  <%= @banking_financial.account_type %>
</p>

<p>
  <b>Account no:</b>
  <%= @banking_financial.account_No %>
</p>

<p>
  <b>Account holders:</b>
  <%= @banking_financial.account_Holders %>
</p>

<p>
  <b>Beneficiary:</b>
  <%= @banking_financial.beneficiary %>
</p>

<p>
  <b>Institution information:</b>
  <%= @banking_financial.institution_Information %>
</p>


<%= link_to 'Edit', edit_banking_financial_path(@banking_financial) %> |
<%= link_to 'Back', banking_financials_path %>