config/routes.rb
Geriatrics::Application.routes.draw do
  resources :funeral_arrangements

  resources :military_histories

  resources :legal_documents

  resources :doctors

  devise_for :users

  get "providers/attorney_insurance_providers"

  get "providers/financial_providers"

  get "providers/healthcare_providers"

  get "providers/caregiver_providers"

 get "providers/attorney_Insurance"

  resources :personal_properties

  resources :legal_doucuments

  resources :insurances

  resources :loans_credit_cards

  resources :banking_financials

  resources :medical_histories

  resources :medications

  resources :clients

  get "post/home"

  get "post/Geriatric_Care_Manager"

  get "post/Geriatric_Client"

  get "post/Providers"

  get "post/Medical_History"

  get "post/Banking_And_Financial"

  get "post/Other_Documents"

  

  

 
end

app/models/banking_financial.rb
class BankingFinancial < ActiveRecord::Base
  belongs_to :user
  attr_accessible :account_Holders, :account_No, :account_type, :beneficiary, :date_Of_Birth, :institution_Information, :social_Security
  validates_presence_of :account_Holders, :account_No, :account_type, :beneficiary, :date_Of_Birth,:social_Security 
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user
  attr_accessible :allergies_info, :blood_type, :date_of_birth, :details_DNR, :firstname, :lastname, :name_healthcare_proxy, :organization, :phone_no

  validates_presence_of :allergies_info, :blood_type, :date_of_birth, :details_DNR, :firstname, :lastname, :name_healthcare_proxy, :organization, :phone_no
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  attr_accessible :address, :name
end

app/models/doctors.rb
class Doctors < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
  belongs_to :user
  attr_accessible :account_Holders, :account_No, :account_Type, :beneficiary, :document, :institution_Information, :insurance_Card
 validates_presence_of :account_Holders, :account_No, :account_Type, :beneficiary, :document, :institution_Information, :insurance_Card
end

app/models/legal_document.rb
class LegalDocument < ActiveRecord::Base
  attr_accessible :do_ot_resuscitate, :health_care_directive, :letter_of_authorization, :location_of_original, :pension_papers, :power_of_attorney, :trust, :will, :wishes
end

app/models/legal_doucument.rb
class LegalDoucument < ActiveRecord::Base
  attr_accessible :do_Not_Resuscitate, :healthcare_Directive, :letter_of_Authorization, :location_of_Original, :pension_Papers, :power_of_Attorney, :trust, :will, :wishes
 validates_presence_of :do_Not_Resuscitate, :healthcare_Directive, :letter_of_Authorization, :location_of_Original, :pension_Papers, :power_of_Attorney, :trust, :will, :wishes
end

app/models/loans_credit_card.rb
class LoansCreditCard < ActiveRecord::Base
  belongs_to :user
  attr_accessible :account_Number, :account_Type, :institution_Information
 validates_presence_of :account_Number, :account_Type, :institution_Information
end

app/models/medical_history.rb
class MedicalHistory < ActiveRecord::Base
  belongs_to :user
  attr_accessible :comments, :date, :date_Of_Onset, :diagnosis_procedure, :documents, :physician, :updater
 validates_presence_of :comments, :date, :date_Of_Onset, :diagnosis_procedure, :documents, :physician, :updater
end

app/models/medication.rb
class Medication < ActiveRecord::Base
  belongs_to :user
  attr_accessible :currently_Taking, :dosage, :frequency, :medication_Photo, :name_Of_Medication, :pharmacy, :prescrbing_Physician, :prescription, :special_Instruvtions
 validates_presence_of :currently_Taking, :dosage, :frequency, :medication_Photo, :name_Of_Medication, :pharmacy, :prescrbing_Physician, :prescription, :special_Instruvtions
end

app/models/military_history.rb
class MilitaryHistory < ActiveRecord::Base
  attr_accessible :_number, :active_or_reserve, :branch_of_service, :military_contact_name, :military_contact_phone, :notes, :pension_or_benefits_phone, :pension_qualified?, :years_of_service
end

app/models/personal_property.rb
class PersonalProperty < ActiveRecord::Base
  belongs_to :user
  attr_accessible :address_Line1, :address_Line2, :city, :item_Location, :make, :model, :notes, :notes, :notes_Collectibles_Valuable, :property_Nickname, :state, :stem_Description, :vehicles, :year, :zip
 validates_presence_of :address_Line1, :address_Line2, :city, :item_Location, :make, :model, :notes, :notes, :notes_Collectibles_Valuable, :property_Nickname, :state, :stem_Description, :vehicles, :year, :zip
end

app/models/user.rb
class User < ActiveRecord::Base
has_one :banking_financial
has_one :client
has_one :insurance
has_one :loans_credit_card
has_one :medical_history
has_one :medication
has_one :personal_property

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/medical_histories_controller.rb
class MedicalHistoriesController < ApplicationController
  # GET /medical_histories
  # GET /medical_histories.json
  def index
    @medical_histories = MedicalHistory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @medical_histories }
    end
  end

  # GET /medical_histories/1
  # GET /medical_histories/1.json
  def show
    @medical_history = MedicalHistory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @medical_history }
    end
  end

  # GET /medical_histories/new
  # GET /medical_histories/new.json
  def new
    @medical_history = MedicalHistory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @medical_history }
    end
  end

  # GET /medical_histories/1/edit
  def edit
    @medical_history = MedicalHistory.find(params[:id])
  end

  # POST /medical_histories
  # POST /medical_histories.json
  def create
    @medical_history = MedicalHistory.new(params[:medical_history])

    respond_to do |format|
      if @medical_history.save
        format.html { redirect_to @medical_history, notice: 'Medical history was successfully created.' }
        format.json { render json: @medical_history, status: :created, location: @medical_history }
      else
        format.html { render action: "new" }
        format.json { render json: @medical_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /medical_histories/1
  # PUT /medical_histories/1.json
  def update
    @medical_history = MedicalHistory.find(params[:id])

    respond_to do |format|
      if @medical_history.update_attributes(params[:medical_history])
        format.html { redirect_to @medical_history, notice: 'Medical history was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @medical_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medical_histories/1
  # DELETE /medical_histories/1.json
  def destroy
    @medical_history = MedicalHistory.find(params[:id])
    @medical_history.destroy

    respond_to do |format|
      format.html { redirect_to medical_histories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/medical_histories_helper.rb
module MedicalHistoriesHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/medical_histories/_form.html.erb
<%= form_for(@medical_history) do |f| %>
  <% if @medical_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medical_history.errors.count, "error") %> prohibited this medical_history from being saved:</h2>

      <ul>
      <% @medical_history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :updater %><br />
    <%= f.text_area :updater %>
  </div>
  <div class="field">
    <%= f.label :diagnosis_procedure %><br />
    <%= f.text_area :diagnosis_procedure %>
  </div>
  <div class="field">
    <%= f.label :date_Of_Onset %><br />
    <%= f.datetime_select :date_Of_Onset %>
  </div>
  <div class="field">
    <%= f.label :physician %><br />
    <%= f.text_field :physician %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="field">
    <%= f.label :documents %><br />
    <%= f.text_area :documents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medical_histories/edit.html.erb
<nav id="top_menu">
<%=render :partial=>'shared/navigation'%>
  </nav>
<h2>Editing Medical History</h2>

<%= render 'form' %>

<%= link_to 'Show', @medical_history %> |
<%= link_to 'Back', medical_histories_path %>

app/views/medical_histories/index.html.erb
<nav id="top_menu">
<%=render :partial=>'shared/navigation'%>
  </nav>
<h1>Listing medical_histories</h1>

<table>
 <!-- <tr>
    <th>Date</th>
    <th>Updater</th>
    <th>Diagnosis procedure</th>
    <th>Date of onset</th>
    <th>Physician</th>
    <th>Comments</th>
    <th>Documents</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>-->

<% @medical_histories.each do |medical_history| %>
  <tr>
    <td><%= medical_history.date %></td>
    <td><%= medical_history.updater %></td>
    <td><%= medical_history.diagnosis_procedure %></td>
    <td><%= medical_history.date_Of_Onset %></td>
    <td><%= medical_history.physician %></td>
    <td><%= medical_history.comments %></td>
    <td><%= medical_history.documents %></td>
    <td><%= link_to 'Show', medical_history %></td>
    <td><%= link_to 'Edit', edit_medical_history_path(medical_history) %></td>
    <td><%= link_to 'Destroy', medical_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Medical history', new_medical_history_path %>

app/views/medical_histories/new.html.erb
<nav id="top_menu">
<%=render :partial=>'shared/navigation'%>
  </nav>
<h2>New medical_history</h2>

<%= render 'form' %>

<!--<#%= link_to 'Back', medical_histories_path %>-->

<%= link_to 'New Client', clients_path %>

app/views/medical_histories/show.html.erb
<nav id="top_menu">
<%=render :partial=>'shared/navigation'%>
  </nav>
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @medical_history.date %>
</p>

<p>
  <b>Updater:</b>
  <%= @medical_history.updater %>
</p>

<p>
  <b>Diagnosis procedure:</b>
  <%= @medical_history.diagnosis_procedure %>
</p>

<p>
  <b>Date of onset:</b>
  <%= @medical_history.date_Of_Onset %>
</p>

<p>
  <b>Physician:</b>
  <%= @medical_history.physician %>
</p>

<p>
  <b>Comments:</b>
  <%= @medical_history.comments %>
</p>

<p>
  <b>Documents:</b>
  <%= @medical_history.documents %>
</p>


<%= link_to 'Edit', edit_medical_history_path(@medical_history) %> |
<%= link_to 'Back', medical_histories_path %>