config/routes.rb
Geriatrics::Application.routes.draw do
  resources :funeral_arrangements

  resources :military_histories

  resources :legal_documents

  resources :doctors

  devise_for :users

  get "providers/attorney_insurance_providers"

  get "providers/financial_providers"

  get "providers/healthcare_providers"

  get "providers/caregiver_providers"

 get "providers/attorney_Insurance"

  resources :personal_properties

  resources :legal_doucuments

  resources :insurances

  resources :loans_credit_cards

  resources :banking_financials

  resources :medical_histories

  resources :medications

  resources :clients

  get "post/home"

  get "post/Geriatric_Care_Manager"

  get "post/Geriatric_Client"

  get "post/Providers"

  get "post/Medical_History"

  get "post/Banking_And_Financial"

  get "post/Other_Documents"

  

  

 
end

app/models/banking_financial.rb
class BankingFinancial < ActiveRecord::Base
  belongs_to :user
  attr_accessible :account_Holders, :account_No, :account_type, :beneficiary, :date_Of_Birth, :institution_Information, :social_Security
  validates_presence_of :account_Holders, :account_No, :account_type, :beneficiary, :date_Of_Birth,:social_Security 
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user
  attr_accessible :allergies_info, :blood_type, :date_of_birth, :details_DNR, :firstname, :lastname, :name_healthcare_proxy, :organization, :phone_no

  validates_presence_of :allergies_info, :blood_type, :date_of_birth, :details_DNR, :firstname, :lastname, :name_healthcare_proxy, :organization, :phone_no
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  attr_accessible :address, :name
end

app/models/doctors.rb
class Doctors < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/funeral_arrangement.rb
class FuneralArrangement < ActiveRecord::Base
  attr_accessible :arrangements_or_celebration_of_life_details, :contact_name, :organization_name, :provider_address, :provider_email, :provider_phone_number
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
  belongs_to :user
  attr_accessible :account_Holders, :account_No, :account_Type, :beneficiary, :document, :institution_Information, :insurance_Card
 validates_presence_of :account_Holders, :account_No, :account_Type, :beneficiary, :document, :institution_Information, :insurance_Card
end

app/models/legal_document.rb
class LegalDocument < ActiveRecord::Base
  attr_accessible :do_ot_resuscitate, :health_care_directive, :letter_of_authorization, :location_of_original, :pension_papers, :power_of_attorney, :trust, :will, :wishes
end

app/models/legal_doucument.rb
class LegalDoucument < ActiveRecord::Base
  attr_accessible :do_Not_Resuscitate, :healthcare_Directive, :letter_of_Authorization, :location_of_Original, :pension_Papers, :power_of_Attorney, :trust, :will, :wishes
 validates_presence_of :do_Not_Resuscitate, :healthcare_Directive, :letter_of_Authorization, :location_of_Original, :pension_Papers, :power_of_Attorney, :trust, :will, :wishes
end

app/models/loans_credit_card.rb
class LoansCreditCard < ActiveRecord::Base
  belongs_to :user
  attr_accessible :account_Number, :account_Type, :institution_Information
 validates_presence_of :account_Number, :account_Type, :institution_Information
end

app/models/medical_history.rb
class MedicalHistory < ActiveRecord::Base
  belongs_to :user
  attr_accessible :comments, :date, :date_Of_Onset, :diagnosis_procedure, :documents, :physician, :updater
 validates_presence_of :comments, :date, :date_Of_Onset, :diagnosis_procedure, :documents, :physician, :updater
end

app/models/medication.rb
class Medication < ActiveRecord::Base
  belongs_to :user
  attr_accessible :currently_Taking, :dosage, :frequency, :medication_Photo, :name_Of_Medication, :pharmacy, :prescrbing_Physician, :prescription, :special_Instruvtions
 validates_presence_of :currently_Taking, :dosage, :frequency, :medication_Photo, :name_Of_Medication, :pharmacy, :prescrbing_Physician, :prescription, :special_Instruvtions
end

app/models/military_history.rb
class MilitaryHistory < ActiveRecord::Base
  attr_accessible :_number, :active_or_reserve, :branch_of_service, :military_contact_name, :military_contact_phone, :notes, :pension_or_benefits_phone, :pension_qualified?, :years_of_service
end

app/models/personal_property.rb
class PersonalProperty < ActiveRecord::Base
  belongs_to :user
  attr_accessible :address_Line1, :address_Line2, :city, :item_Location, :make, :model, :notes, :notes, :notes_Collectibles_Valuable, :property_Nickname, :state, :stem_Description, :vehicles, :year, :zip
 validates_presence_of :address_Line1, :address_Line2, :city, :item_Location, :make, :model, :notes, :notes, :notes_Collectibles_Valuable, :property_Nickname, :state, :stem_Description, :vehicles, :year, :zip
end

app/models/user.rb
class User < ActiveRecord::Base
has_one :banking_financial
has_one :client
has_one :insurance
has_one :loans_credit_card
has_one :medical_history
has_one :medication
has_one :personal_property

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
  # GET /insurances
  # GET /insurances.json
  def index
    @insurances = Insurance.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @insurances }
    end
  end

  # GET /insurances/1
  # GET /insurances/1.json
  def show
    @insurance = Insurance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @insurance }
    end
  end

  # GET /insurances/new
  # GET /insurances/new.json
  def new
    @insurance = Insurance.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @insurance }
    end
  end

  # GET /insurances/1/edit
  def edit
    @insurance = Insurance.find(params[:id])
  end

  # POST /insurances
  # POST /insurances.json
  def create
    @insurance = Insurance.new(params[:insurance])

    respond_to do |format|
      if @insurance.save
        format.html { redirect_to @insurance, notice: 'Insurance was successfully created.' }
        format.json { render json: @insurance, status: :created, location: @insurance }
      else
        format.html { render action: "new" }
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /insurances/1
  # PUT /insurances/1.json
  def update
    @insurance = Insurance.find(params[:id])

    respond_to do |format|
      if @insurance.update_attributes(params[:insurance])
        format.html { redirect_to @insurance, notice: 'Insurance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insurances/1
  # DELETE /insurances/1.json
  def destroy
    @insurance = Insurance.find(params[:id])
    @insurance.destroy

    respond_to do |format|
      format.html { redirect_to insurances_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/insurances/_form.html.erb
<%= form_for(@insurance) do |f| %>
  <% if @insurance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@insurance.errors.count, "error") %> prohibited this insurance from being saved:</h2>

      <ul>
      <% @insurance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account_Type %><br />
    <%= f.text_field :account_Type %>
  </div>
  <div class="field">
    <%= f.label :account_No %><br />
    <%= f.number_field :account_No %>
  </div>
  <div class="field">
    <%= f.label :account_Holders %><br />
    <%= f.text_field :account_Holders %>
  </div>
  <div class="field">
    <%= f.label :beneficiary %><br />
    <%= f.text_field :beneficiary %>
  </div>
  <div class="field">
    <%= f.label :institution_Information %><br />
    <%= f.text_area :institution_Information %>
  </div>
  <div class="field">
    <%= f.label :document %><br />
    <%= f.text_area :document %>
  </div>
  <div class="field">
    <%= f.label :insurance_Card %><br />
    <%= f.text_field :insurance_Card %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/insurances/edit.html.erb
<nav id="top_menu">
<%=render :partial=>'shared/navigation'%>
  </nav>
<h1>Editing insurance</h1>

<%= render 'form' %>

<%= link_to 'Show', @insurance %> |
<%= link_to 'Back', insurances_path %>

app/views/insurances/index.html.erb
<nav id="top_menu">
<%=render :partial=>'shared/navigation'%>
  </nav>
<h1>Listing insurances</h1>

<table>
  <tr>
    <th>Account type</th>
    <th>Account no</th>
    <th>Account holders</th>
    <th>Beneficiary</th>
    <th>Institution information</th>
    <th>Document</th>
    <th>Insurance card</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @insurances.each do |insurance| %>
  <tr>
    <td><%= insurance.account_Type %></td>
    <td><%= insurance.account_No %></td>
    <td><%= insurance.account_Holders %></td>
    <td><%= insurance.beneficiary %></td>
    <td><%= insurance.institution_Information %></td>
    <td><%= insurance.document %></td>
    <td><%= insurance.insurance_Card %></td>
    <td><%= link_to 'Show', insurance %></td>
    <td><%= link_to 'Edit', edit_insurance_path(insurance) %></td>
    <td><%= link_to 'Destroy', insurance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Insurance', new_insurance_path %>

app/views/insurances/new.html.erb
<nav id="top_menu">
<%=render :partial=>'shared/navigation'%>
  </nav>
<h1>New insurance</h1>

<%= render 'form' %>

<!--<#%= link_to 'Back', insurances_path %>-->

<%= link_to 'New Client', clients_path %>

app/views/insurances/show.html.erb
<nav id="top_menu">
<%=render :partial=>'shared/navigation'%>
  </nav>
<p id="notice"><%= notice %></p>

<p>
  <b>Account type:</b>
  <%= @insurance.account_Type %>
</p>

<p>
  <b>Account no:</b>
  <%= @insurance.account_No %>
</p>

<p>
  <b>Account holders:</b>
  <%= @insurance.account_Holders %>
</p>

<p>
  <b>Beneficiary:</b>
  <%= @insurance.beneficiary %>
</p>

<p>
  <b>Institution information:</b>
  <%= @insurance.institution_Information %>
</p>

<p>
  <b>Document:</b>
  <%= @insurance.document %>
</p>

<p>
  <b>Insurance card:</b>
  <%= @insurance.insurance_Card %>
</p>


<%= link_to 'Edit', edit_insurance_path(@insurance) %> |
<%= link_to 'Back', insurances_path %>