config/routes.rb
Geriatrics::Application.routes.draw do
  resources :funeral_arrangements

  resources :military_histories

  resources :legal_documents

  resources :doctors

  devise_for :users

  get "providers/attorney_insurance_providers"

  get "providers/financial_providers"

  get "providers/healthcare_providers"

  get "providers/caregiver_providers"

 get "providers/attorney_Insurance"

  resources :personal_properties

  resources :legal_doucuments

  resources :insurances

  resources :loans_credit_cards

  resources :banking_financials

  resources :medical_histories

  resources :medications

  resources :clients

  get "post/home"

  get "post/Geriatric_Care_Manager"

  get "post/Geriatric_Client"

  get "post/Providers"

  get "post/Medical_History"

  get "post/Banking_And_Financial"

  get "post/Other_Documents"

  

  

 
end

app/models/banking_financial.rb
class BankingFinancial < ActiveRecord::Base
  belongs_to :user
  attr_accessible :account_Holders, :account_No, :account_type, :beneficiary, :date_Of_Birth, :institution_Information, :social_Security
  validates_presence_of :account_Holders, :account_No, :account_type, :beneficiary, :date_Of_Birth,:social_Security 
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user
  attr_accessible :allergies_info, :blood_type, :date_of_birth, :details_DNR, :firstname, :lastname, :name_healthcare_proxy, :organization, :phone_no

  validates_presence_of :allergies_info, :blood_type, :date_of_birth, :details_DNR, :firstname, :lastname, :name_healthcare_proxy, :organization, :phone_no
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  attr_accessible :address, :name
end

app/models/doctors.rb
class Doctors < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
  belongs_to :user
  attr_accessible :account_Holders, :account_No, :account_Type, :beneficiary, :document, :institution_Information, :insurance_Card
 validates_presence_of :account_Holders, :account_No, :account_Type, :beneficiary, :document, :institution_Information, :insurance_Card
end

app/models/legal_document.rb
class LegalDocument < ActiveRecord::Base
  attr_accessible :do_ot_resuscitate, :health_care_directive, :letter_of_authorization, :location_of_original, :pension_papers, :power_of_attorney, :trust, :will, :wishes
end

app/models/legal_doucument.rb
class LegalDoucument < ActiveRecord::Base
  attr_accessible :do_Not_Resuscitate, :healthcare_Directive, :letter_of_Authorization, :location_of_Original, :pension_Papers, :power_of_Attorney, :trust, :will, :wishes
 validates_presence_of :do_Not_Resuscitate, :healthcare_Directive, :letter_of_Authorization, :location_of_Original, :pension_Papers, :power_of_Attorney, :trust, :will, :wishes
end

app/models/loans_credit_card.rb
class LoansCreditCard < ActiveRecord::Base
  belongs_to :user
  attr_accessible :account_Number, :account_Type, :institution_Information
 validates_presence_of :account_Number, :account_Type, :institution_Information
end

app/models/medical_history.rb
class MedicalHistory < ActiveRecord::Base
  belongs_to :user
  attr_accessible :comments, :date, :date_Of_Onset, :diagnosis_procedure, :documents, :physician, :updater
 validates_presence_of :comments, :date, :date_Of_Onset, :diagnosis_procedure, :documents, :physician, :updater
end

app/models/medication.rb
class Medication < ActiveRecord::Base
  belongs_to :user
  attr_accessible :currently_Taking, :dosage, :frequency, :medication_Photo, :name_Of_Medication, :pharmacy, :prescrbing_Physician, :prescription, :special_Instruvtions
 validates_presence_of :currently_Taking, :dosage, :frequency, :medication_Photo, :name_Of_Medication, :pharmacy, :prescrbing_Physician, :prescription, :special_Instruvtions
end

app/models/military_history.rb
class MilitaryHistory < ActiveRecord::Base
  attr_accessible :_number, :active_or_reserve, :branch_of_service, :military_contact_name, :military_contact_phone, :notes, :pension_or_benefits_phone, :pension_qualified?, :years_of_service
end

app/models/personal_property.rb
class PersonalProperty < ActiveRecord::Base
  belongs_to :user
  attr_accessible :address_Line1, :address_Line2, :city, :item_Location, :make, :model, :notes, :notes, :notes_Collectibles_Valuable, :property_Nickname, :state, :stem_Description, :vehicles, :year, :zip
 validates_presence_of :address_Line1, :address_Line2, :city, :item_Location, :make, :model, :notes, :notes, :notes_Collectibles_Valuable, :property_Nickname, :state, :stem_Description, :vehicles, :year, :zip
end

app/models/user.rb
class User < ActiveRecord::Base
has_one :banking_financial
has_one :client
has_one :insurance
has_one :loans_credit_card
has_one :medical_history
has_one :medication
has_one :personal_property

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/shared/_aside.html.erb
<h2>Manager and Clients Enter The Information </h2>


<h2><%=link_to "Sign Up", clients_path ,:alt=>'Manager and Clients Enter The Information'%></h2>

app/views/shared/_menu.html.erb
<div id="new_div1">


  <%= link_to '1.New Client Details', new_client_path %></br>
  <%= link_to '2.Banking financial Details ', new_banking_financial_path %></br>
  <%= link_to '3.Insurance Details', new_insurance_path %></br>
  <%= link_to '4.Loans credit card Details', new_loans_credit_card_path %></br>
  <%= link_to '6.Medical history Details', new_medical_history_path %></br>
  <%= link_to '7.Medication Details', new_medication_path %></br>
  <%= link_to '8.Personal property Details', new_personal_property_path %></br>
  <%= link_to "8.Enter About Funeral Arrangements",clients_path %></br>
  <%= link_to "9.Enter Military History",clients_path %></br>
  <%=link_to "10.Enter Employment History",clients_path%></br>
  <%=link_to "11.Enter Pet Information",clients_path%></br>
  <%=link_to "12.Enter Utilities Information",clients_path%></br></br></br></br></br></br>
</div>

app/views/shared/_navigation.html.erb
 <div id="new_div">
	<ul>
        <li><%=link_to_unless_current"Home" ,post_home_path,:alt=>'Home'%></li>
		<li><%=link_to_unless_current "Geriatric_Care_Manager", post_Geriatric_Care_Manager_path, :alt=>'Geriatric Care Manager'%></li>
		<li><%=link_to_unless_current "Geriatric_Client", post_Geriatric_Client_path, :alt=>'Geriatric Client'%></li>
		<li><%=link_to_unless_current "Medical_History",post_Medical_History_path,:alt=>'Medical History'%></li>
        <li><%=link_to_unless_current "Banking_And_Financial" ,post_Banking_And_Financial_path,:alt=>'Banking_And_Financial'%></li>
		<li><%=link_to_unless_current "Other_Documents",post_Other_Documents_path,:alt=>'Other Document'%></li>
      <li><%=link_to_unless_current "Providers",post_Providers_path,:alt=>'Providers'%></li>
	</ul>
</div>